ALTER TABLE supplier ADD COLUMN biz_no VARCHAR(20) DEFAULT NULL AFTER email;
ALTER TABLE supplier ADD COLUMN representative VARCHAR(50) DEFAULT NULL AFTER biz_no;
ALTER TABLE supplier ADD COLUMN phone VARCHAR(30) DEFAULT NULL AFTER representative;
ALTER TABLE supplier ADD COLUMN address VARCHAR(300) DEFAULT NULL AFTER phone;
ALTER TABLE supplier ADD COLUMN memo TEXT DEFAULT NULL AFTER address;
